CREATE TABLE sales (
row_id INT PRIMARY KEY,
order_id VARCHAR(20) NOT NULL,
order_date DATE,
ship_date DATE,
ship_mode VARCHAR(20),
customer_id VARCHAR(20) NOT NULL,
customer_name TEXT,
segment VARCHAR(15),
country VARCHAR(15),
city VARCHAR(20),
states VARCHAR(20),
postal_code VARCHAR(5),
region VARCHAR(10),
product_id VARCHAR(20) NOT NULL,
category VARCHAR(20),
sub_category VARCHAR(30),
product_name TEXT,
sales NUMERIC(10,2),
quantity INT,
discout NUMERIC(10,2),
profit NUMERIC(10,4),
profit_margin NUMERIC(5,4)
)